config/routes.rb
Blog::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root "posts#index"

  scope "bb" do
     get "postsjson/:id", to: "posts#postsjson", defaults: {format: :json}
     get "posts/list_posts", to: "posts#list_posts" , defaults: {format: :json}
  end

  resources :posts

  namespace :admin do
    resources :posts
  end
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:postsjson,:show, :index, :list_posts]
  def index
  end

  def new
  end

  def update
  end

  def create
  end

  def list_posts
       array = Post.select(:id,:title,:body).limit(20).order('id desc')
       array.each { |post|
           post.body=post.body[0...300]+"......."
       }
       render json: array
  end

  def postsjson
     render json: Post.find_by(id: params[:id])
  end

  def show
  
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>xXRanXieXxBlog</title>

 	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
 	  <script type="text/javascript"
  		src="https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  	  <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?autoload=false&lang=ruby&skin=sunburst"></script>
  </head>

<body>

<div class="container">
	<div class="row">
	   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
		<div id="hero" class="jumbotron col-xs-12 col-md-12">
			<div class="container">
				<%= render 'partials/banner'%>
				<div id="menu" class="col-xs-9 col-md-9">
					<div class="btn-group">
						  <button id="postslist" type="button" class="btn btn-danger"> <span class="btn-text">Posts</span></button>
						   <button id="tipslist" type="button" class="btn btn-danger"><span class="btn-text">Tips</span></button>
						   <button id="noteslist" type="button" class="btn btn-danger"><span class="btn-text">Notes</span></button>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="content-wrapper" class="row">	
			<div id="center" class="col-xs-9 col-sm-9">	
					<%= yield %>
			</div>

			<div id="right" class="col-xs-3 col-sm-3">
				<div class="col-xs-12">
					<% if user_signed_in?%>
					   Signed in as <%= current_user.email %> <br>
					   <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
					<% else %>
					<%= render 'partials/login' %>
					<% end %>
				</div>
			</div>

	</div>

	<div class="row">
		<div id="footer" class="col-xs-12 col-md-12">
			<p> Last updated: <%= Time.now %>...well,I lied :p</p>
		</div>
	</div>
</div>


  </body>
</html>

app/views/partials/_banner.html.erb
<h1 class="black"> SkarLit</h1>
<h2 class="white" style="text-indent:50px">Blogging on web dev</h2> 

app/views/partials/_login.html.erb
 

<!--
 <div class="form-group">
    <label for="userid">UserId</label>
    <input type="email" class="form-control" id="userid" placeholder="user id">
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" id="password" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
-->

<%= form_for :user, url: user_session_path, html:{class:"form-group"} do |f| %>
	<%= f.label :email %> <br>
	<%= f.text_field :email, class:"form-control" %> <br>

	<%= f.label :password %> <br>
	<%= f.password_field :password , class:"form-control"%> <br>
	<%= f.submit "Login", class:"btn btn-default", id: "login"%> 
  New user? <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/list_posts.html.erb
<% @posts.each do |post| %>
   <%= link_to post.title, posts_path(post) %> 
   <br>
 <% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>